volumes:
  cargo-cache: {}
  db:
services:
  encurtador-de-url:
    container_name: encurtador-de-url
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: .
      target: development
    command:
      - sh
      - -c
      - |
        RUST_LOG=debug cargo watch -w src -x run
    ports:
      - 3000:3000
    volumes:
      - .:/opt/encurtador-de-url/app
      - ./target:/usr/local/cargo/target
    restart: unless-stopped
    extra_hosts:
      - "encurtador-de-url.dev:172.17.0.1"
  postgres:
    container_name: postgres
    image: postgres:14.9
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
networks:
  default:
    driver: bridge
    name: development-network
