apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    uid: "adjw8shzje874b"
    jsonData:
      tlsSkipVerify: true
